sudo: required
language: bash
services: docker
env:
  matrix:
  - ARCH=x86_64 PUID=1000 PGID=1000
  - ARCH=armhf PUID=1001 PGID=1001
  global:
  - secure: Umk9NJ5R8YRmGa2Q9KaK+jZsJ9IzfRXYY6tdIui1goapBOoJNXOYymz+uqsNyHsC+FJNjwonAXhEKtA5mbJRs+jo571deCYa/YrYzK1vDd8Z4nl/mczgn1sQ7QXHEyRbeNshu9/fPGrz4XFPnK/QuDMLn1tOqiG4OJsftVZWj1aC195Y/oP1pdNbdMyM5w0RR7plNakDxD27vki3MyMiZmSctBS7sL3sk8pqL+I0KyTuBC0Ojqo3WYUD3XPON83Op1RH1mSl87xUqZ2EBJGD1mIMcWYX5u12uF0wvfjvYXep0dLrUQIlOyl+OsotsnnyuZ5x9VEEQ+WNk4o+fdTLf/qlmqSBR4ADSDHKeAEBGAXK/m/UXB3I/8vu3n+jetUZ9vdMGTfoc4olBxGVItJfoMYWZHU2xhQ3MMDdH8OlZ+8evdum3wLQbMG+svsVAvaYgR421Vo0a1aikowAN2mljoNrV4XdvrwsNdvgvPLCmKjSNDiRnKpxjVMhVtVoJ4Z3bFLlwjnmBN7bdTOfQvDMxB89OddSWWKfjuOodGyV/E04Q1mjJ3KxSAm+fN3kjhCObKhF1rk1/SZGdMUtHW40DXR91kASD2N7sN93mpbKWNrpy2KRwBVJTvwGFOVwjEwIRGTVkHmgEGJLIsVoShMk84Ty3vbT6JhMMkj8BO20ZbY=
  - secure: i2o0S/54IlDK6rYiQGDTjhVnexLQah8FrxQPplBtc6bjwu7DJCWzfNcyiVI2Dei/k2Yq3FTPoa/rJY0YZURiQOHAIXbRt0v5h4ry4K4O5ruwvk3xZWXug9JV839NZQWdAbnwVP/S5CVNyVHfj6KpFBvC62qlS1v9di/ENb526vQfBga/r3G1abZg8louyVzSdpZapa87718Gddk07UP3IKsSh9T2Zc1ixbRjhXIWF9RZ35eY8+yne8BZ07JlhY2kXLNYjnBWUg6+P1hEOWR9ulv/3nqz0GyqzstDr8XP1XNhHRWa4AlLGOIMwBOXQ7ij3MjZiCKbe1DTF9jbbZS2HdB729a/ve/vM577BQd1reGHMbyy8HXO3qOQAIbrwWoj2LYB2QEGuYr8HaPWn6jIV8nxMS0jaOeWC5fkNQ0yHnZMFcLj0GmRtUMkiAtbztWmnZkKSRrCpaydAIv4R4VzjOJsdFjpILqxYOd+QQE7m0b6ParwZckyRRbNfKtYb5iAbv5GT0ecKBCIQBTpUQVQIeIfTQIRR3b0RVCTKTatGC6knPQ6behcrUM/nsMbddRTStcf2Vw25MSg8ZlH3l9qEuWYBd7LqDsXkrEuEZ0nobV+cYMaktG9dM2u30pz43YjvyyAkXO+t1wgbhfI/8zoHnLPH5JuHN0XBslKq5TlQ2A=
install: true
before_script:
- docker --version
- make --version
script:
- make ARCH=${ARCH} PUID=${PUID} PGID=${PGID} build test
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- make ARCH=${ARCH} push
after_script:
- docker logout
- make clean
