sudo: required
language: bash
services: docker
env:
  matrix:
  - ARCH=x86_64 PUID=1000 PGID=1000
  - ARCH=armhf PUID=1001 PGID=1001
  global:
  - secure: WSc3MCvmd0VrKfIVkxld8W+Bi909VCS/9xbZPiVjxao5+uPsHNi3LHYwjeV8j+z86XKXKl9nk59RvDox2aqjggviYtWrUPBLXuMeL11myD0D65cru1veeV2OZMhpWUhUs3460K5ZsNX4QZMO7XUuOrKeNoFCOFJB2TmMJOoMX/RnTyNuFpBRH6HABR268qZ7rI2yHH8cnIgrH4S/AHhRa8Ouv4/ClPjUzcGzQB1YTWO8fD3pu7FUF5eE79lkbwF9DAFUF+PAC3OboSDoohz34APFU1uhtyOGT/E9TJi/9Y0RBEkY4FLE4pR4mSyOCzKrfTG14uca6xWukwHSeIUVpP/EzkxoGxswl3j4UPaHaLc1YeqQfoGJ6mNwOYUrY1A/JXD22ImpdcmyT2NY+nyvzaWis2ZfL+iy9wBSsylSpAce2Edp97LwG6DZfAZQqqv/ZCsGUicdRGtsJmOIr6tpCg16iWXStBy70YulU04Tvb7Vg5dhlpxNjeiOsmn2o9Bp/FGBg7V8sBcF7AX/TfoAkifRt8lSJz+ii4OfbPK1Y8o6cmv+GyiaQquICpU2WGK91mLrIkrX/9vzioyOUJ/Y50IxSElvdEi+ObKoM59ESHZGiFwZ4apWDhpo4ti8+8IAlnowjyyictGx5JpWu5GYzCVO9Cq+mf6MWfh8CkyiVN8=
  - secure: DxmBRIPCPhiJxwagLE1PnbaOpXaa0pRYFJsD07B/3hwafFvmtlKj+qFaYEX86e/6ZEOjvwxrfhcjKPBsevuE5Z65bI9kTCDkVoGqH6TpWs7upMOIyDcmm+fYm/e4fK6q5sox/2FFrmP6/QU8YhNN1E4IuwtFHBt2QODFUQ2ytaGwqGYh1ECFH2DrfP2sNeoj8HJE6m7zpmvgYuvI9d4QO9/dZseNojrK5OSeHVuh++hvI5itoC+GbswAoXHup1/Us8TDMhYgQXq9qmqFDvU5olsGm1SxsTd662ACoplHxgqPRsCf7rXNc3M7yWf0xUF0Xsj7w/Q2aMsaJvb+C2PHKBUV+3wUANzf/AXam1PyjYoaqvReaCBfX0osRy/vZSIUq4zdAyBXPbmRr9VLpI+fCOIF015+lIAvGyfL4nmoeVNCqHgTX+MOooBHkeZNQJ5gzJU6Ler3fNZ9H/3ENp6GWRA6Cf362jWoi5TAX/8LUcwhFTtg1ov2uwC7csLou3z5a1rtUS7E9XXTW5dCYWmsIXJOZb3eA+JGqcPer9zKRpbO9eTwOkEheQTbtKtrV+vK2TujLsZ6geIWuttpoLF8iqqCXMAEizvs/SYllzELatUYkrt2J0eAAsfx3jT0XDwDkw0gWjWkd8vLgiX5++Z5KZ1h6RTGnIGZLooCSLfZXQU=
install: true
before_script:
- docker --version
- make --version
script:
- make ARCH=${ARCH} PUID=${PUID} PGID=${PGID} build test
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- make ARCH=${ARCH} push
after_script:
- docker logout
- make clean
